#config_version=6

mode:
  start_events: start_mode_gizmo_multi
  stop_events: stop_mode_gizmo_multi
  priority: 1000

event_player:
  timer_hurryup_timer_complete: stop_mode_gizmo_multi
  hurryup_hit: stop_mode_gizmo_multi
  timer_hurryup_timer_tick: 
    hurryup_value:
      current_hurryup:
        type: int
        value: 100_000 - ticks * 2_000

shots:
  gizmo_multi:
    switch: s_ramp_1

slide_player:
  mode_gizmo_multi_started: gizmo_multi

timers: 
  gizmo_multi_timer:
    end_value: 25
    start_running: true
    tick_interval: 200ms

variable_player:
  gizmo_multi_hit:
    score: 100_000 - device.timers.hurryup_timer.ticks * 2_000
